apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: pythonapp
          image: pythonapp:latest
          ports:
            - containerPort: 8000
         